config/routes.rb
Myapp::Application.routes.draw do

  resources :prelaunch_subscribers, only: [:new, :create, :destroy, :show]

  namespace :admin do
    resources :sessions, only: [:new, :destroy] do
      get :signout, to: :destroy, as: :signout
      get :error
    end

    namespace :dashboard do
      get "home"
      get "subscribers"
    end

    root to: 'dashboard#home'

    get 'auth/google_oauth2/callback', to: 'sessions#create'
  end

  get "home/index"

  root to: 'prelaunch_subscribers#new'

end

app/models/prelaunch_subscriber.rb
class PrelaunchSubscriber < ActiveRecord::Base
  validates_presence_of :email, message: 'Please enter your email address.'
  validates_uniqueness_of :email, message: 'That email is already on the subscription list.'
  validates_format_of :email,
    with: /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/i,
    message: 'Please use a valid email address.'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminsController
  def home

  end

  def subscribers
    @subscribers = PrelaunchSubscriber.all
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < AdminsController
  skip_before_filter :ensure_authorized
  ADMIN_EMAILS = ['peihongli94@gmail.com', 'jasonjypark@gmail.com'].freeze

  def new
    redirect_to '/admin/auth/google_oauth2'
  end

  def create
    auth = request.env['omniauth.auth']
    if auth && auth['info']['email'].in?(ADMIN_EMAILS)
      set_admin_session(auth['info'])
      redirect_to session.delete(:return_to) || admin_dashboard_home_path
    else
      redirect_to root_path
    end
  end

  def destroy
    expire_admin_session
    redirect_to root_path
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard

  end

  def subscribers
    @subscribers = PrelaunchSubscriber.all
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :ensure_authorized

  def set_admin_session(details)
    session[:admin_auth] = details
  end

  def ensure_authorized
    return if session[:admin_auth]

    session[:return_to] = request.fullpath
    redirect_to new_admin_session_path
  end

  def expire_admin_session
    session[:admin_auth] = nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/prelaunch_subscribers_controller.rb
class PrelaunchSubscribersController < ApplicationController
  def new
    @prelaunch_subscriber = PrelaunchSubscriber.new
  end

  def create
    @prelaunch_subscriber = PrelaunchSubscriber.new(params[:prelaunch_subscriber].permit(:email))

    if @prelaunch_subscriber.save
      flash[:success] = "You have been subscribed"
      redirect_to new_prelaunch_subscriber_path
    else
      flash[:error] = "You have entered an invalid email"
      redirect_to new_prelaunch_subscriber_path
    end
  end

  def destroy
    @subscriber = PrelaunchSubscriber.find(params[:id])
    @subscriber.destroy
    redirect_to admin_subscribers_path
  end
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prelaunch_subscribers_helper.rb
module PrelaunchSubscribersHelper
end

app/views/admin/dashboard.html.erb
<div class='col-md-8 col-md-offset-2'>
  <p>Subscriber Count: <%= PrelaunchSubscriber.count %></p>
</div>

app/views/admin/dashboard/home.html.erb
<div class='col-md-8 col-md-offset-2'>
  <p>Subscriber Count: <%= PrelaunchSubscriber.count %></p>
</div>

app/views/admin/dashboard/subscribers.html.erb
<div class='col-md-8 col-md-offset-2'>
  <table class="table">
    <tr>
      <th>Email</th>
      <th>Date</th>
      <th>Options</th>
    </tr>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.email %></td>
        <td><%= subscriber.created_at %></td>
        <td>
          <%= link_to "mailto:#{subscriber.email}" do %>
            <i class="fa fa-envelope fa-lg dark-icon"></i>
          <% end %>
          <%= link_to prelaunch_subscriber_path(subscriber), method: :delete do %>
            <i class="fa fa-ban fa-lg dark-icon"></i>
          <% end %>
        </td>
      </tr>
    <% end %>

  </table>
</div>

app/views/home/index.html.erb
<p>This is your landing page.</p>

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GR1P", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", admin_dashboard_home_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Subscribers <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "All", admin_dashboard_subscribers_path %></li>
            <li><a href="#">Realistic</a></li>
            <li><a href="#">Suspicious</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DigitalOcean Rails Application</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
<%= render partial: "layouts/admin_navbar" %>
<%= yield %>

</body>
</html>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DigitalOcean Rails Application</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
<%= render partial: "layouts/admin_navbar" %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GR1P</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prelaunch_subscribers/new.html.erb
<div class="header">
  <%= render partial: "shared/flash_messages", flash: flash %>
  <div class="header-text">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="header-title"><b>GR1P is Coming Soon</b></h1>
      <br>
      <div class="header-intro">
        <p>GR1P is a network that allows you to connect with fellow enthusiasts. It allows you to find inspiration, make new friends, discover new events, and show off your build to the world.</p>
        <p>Sign up to be notified for the beta launch!</p>
      </div>

      <%= form_for @prelaunch_subscriber, url: prelaunch_subscribers_path do |f| %>
        <%= f.text_field :email, class: 'header-field' %>
        <% if @prelaunch_subscriber.errors[:email] %>
          <div class="form-error"><p><%= @prelaunch_subscriber.errors[:email].first %></p></div>
        <% end %>
        <br>
        <%= link_to 'Blog', 'http://www.GR1P.kinja.com', class: 'btn btn-large btn-default btn-subscribe' %>
        <%= f.submit 'Add me to the list', class: 'btn btn-large btn-default btn-subscribe' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>">
    <button class="close" data-dismiss="alert">×</button>
    <p><%= message %></p>
  </div>
<% end %>